spring:
  boot:
    admin:
      url: http://localhost:8770/
server:
  port: 8080
info:
  app:
    name: simple-jpa
    description: Simple JPA app that loads information to an in memory H2 database using Spring Data Rest and JPA
    version: 0.0.1
    encoding: UTF-8
    java:
      source: 1.8
      target: 1.8
    java-vendor: ${java.specification.vendor}